food_delivery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

urlpatterns = [
    path('', include('home.api.urls')),
    path("admin/", admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI:
    path(
        "api/swagger/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # api urls
    path(
        "api/token/",
        TokenObtainPairView.as_view(),
        name="token_obtain_pair"
        ),
    path("api/token/refresh/",
         TokenRefreshView.as_view(),
         name="token_refresh"
         ),
    path('user/', include('user.urls')),
    path('api/users/', include('user.api.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('api/restaurants/', include('restaurant.api.urls')),
    path('order/', include('order.urls')),
    path('api/orders/', include('order.api.urls')),
    path('driver/', include('driver.urls')),
    path('api/drivers/', include('driver.api.urls')),
    path('payment/', include('payment.urls')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

user/urls.py
from django.urls import path
from .views import (
    RegisterView,
    LoginView,
    SuccessRegisterView,
    RestaurantDashboardView,
    CustomerDashboardView,
    DriverDashboardView,
    LogoutView,
    UserBalanceCreateView,
    UserBalanceAddView,
    UserBalanceListView
)

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path(
        "success-register/",
        SuccessRegisterView.as_view(),
        name="success-register"
        ),
    path('restaurants-page/', RestaurantDashboardView.as_view(), name='restaurants-page'),
    path('orders-page/', CustomerDashboardView.as_view(), name='orders-page'),
    path('drivers-page/', DriverDashboardView.as_view(), name='drivers-page'),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('userbalance/create/', UserBalanceCreateView.as_view(), name='user-balance-create'),
    path('userbalance/update/<int:pk>/', UserBalanceAddView.as_view(), name='user-balance-update'),
    path('userbalance/', UserBalanceListView.as_view(), name='user-balance-list'),
]

driver/models.py
from django.db import models
from user.models import User
from order.models import Order


class Driver(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=15)
    vehicle_type = models.CharField(max_length=30)
    vehicle_number = models.CharField(max_length=15)
    is_available = models.BooleanField()
    current_location = models.CharField(max_length=255, blank=True, null=True)
    rating = models.FloatField(default=0.0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name


class Delivery(models.Model):
    class Deliverystatus(models.IntegerChoices):
        pending = (
            1,
            "Pending",
        )
        in_progress = (
            2,
            "In Progress",
        )
        completed = (
            3,
            "Completed",
        )
        failed = 4, "Failed"

    order = models.OneToOneField(Order, on_delete=models.CASCADE)
    driver = models.ForeignKey(
        "Driver",
        on_delete=models.CASCADE,
    )
    delivery_address = models.CharField(max_length=255)
    delivery_status = models.IntegerField(choices=Deliverystatus.choices)
    assigned_at = models.DateTimeField()
    delivered_at = models.DateTimeField()

    def __str__(self):
        return f"Delivery for Order #{self.order.id} - {self.delivery_status}"

templates/delivery/delivery_form.html
{% block content %}
<div class="page-body-wrapper">
    <div class="container">
        <h2 class="page-title">delivery</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
        <a href="{% url 'deliverys-list' %}" class="btn btn-secondary">Back to delivery</a>
    </div>
</div>
{% endblock %}

templates/delivery/delivery_list.html
{% block content %}
<div class="container mt-4">
    <h2 class="page-title mb-4">delivery List</h2>
    <div class="d-flex mb-4">
        <div class="ml-auto">
            <a href="{% url 'delivery-create' %}" class="btn btn-primary">Add delivery</a>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>ORDER</th>
                <th>DRIVER</th>
                <th>DELIVERY ADDREESS</th>
                <th>DELIVERY STATUS</th>
                <th>ASSIGNED AT</th>
                <th>DELIVERED AT</th>
            </tr>
        </thead>
        <tbody>
            {% for delivery in deliverys %}
            <tr>
                <td>{{ delivery.id }}</td>
                <td>{{ delivery.order }}</td>
                <td>{{ delivery.driver }}</td>
                <td>{{ delivery.delivery_address }}</td>
                <td>{{ delivery.get_delivery_status_display }}</td>
                <td>{{ delivery.assigned_at }}</td>
                <td>{{ delivery.delivered_at }}</td>
                  <td>
                    <a href="{% url 'delivery-update' delivery.id %}" class="btn btn-edit">Edit</a>
                    <form action="{% url 'delivery-delete' delivery.id %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-delete">Delete</button>
                    </form>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5" class="no-data">No deliverys available.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}